CREATE TABLE supply_chain (
    product_type VARCHAR(50),
    sku VARCHAR(20),
    price NUMERIC(12,2),
    availability INTEGER,
    number_of_products_sold INTEGER,
    revenue_generated NUMERIC(14,2),
    customer_demographics VARCHAR(50),
    stock_levels INTEGER,
    lead_times INTEGER,
    order_quantities INTEGER,
    shipping_times INTEGER,
    shipping_carriers VARCHAR(50),
    shipping_costs NUMERIC(12,2),
    supplier_name VARCHAR(50),
    location VARCHAR(100),
    lead_time INTEGER,
    production_volumes INTEGER,
    manufacturing_lead_time INTEGER,
    manufacturing_costs NUMERIC(12,2),
    inspection_results VARCHAR(20),
    defect_rates NUMERIC(10,4),
    transportation_modes VARCHAR(50),
    routes VARCHAR(50),
    costs NUMERIC(14,2)
);
